//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/krateoplatformops/git-provider/apis/common/v1alpha1"
	"github.com/krateoplatformops/provider-runtime/apis/common/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromResource) DeepCopyInto(out *FromResource) {
	*out = *in
	if in.FromYaml != nil {
		in, out := &in.FromYaml, &out.FromYaml
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.FromRef != nil {
		in, out := &in.FromRef, &out.FromRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.FromString != nil {
		in, out := &in.FromString, &out.FromString
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromResource.
func (in *FromResource) DeepCopy() *FromResource {
	if in == nil {
		return nil
	}
	out := new(FromResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalResource) DeepCopyInto(out *LocalResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalResource.
func (in *LocalResource) DeepCopy() *LocalResource {
	if in == nil {
		return nil
	}
	out := new(LocalResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalResourceList) DeepCopyInto(out *LocalResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LocalResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalResourceList.
func (in *LocalResourceList) DeepCopy() *LocalResourceList {
	if in == nil {
		return nil
	}
	out := new(LocalResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalResourceOpts) DeepCopyInto(out *LocalResourceOpts) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalResourceOpts.
func (in *LocalResourceOpts) DeepCopy() *LocalResourceOpts {
	if in == nil {
		return nil
	}
	out := new(LocalResourceOpts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalResourceSpec) DeepCopyInto(out *LocalResourceSpec) {
	*out = *in
	if in.PlaceholdersToOverride != nil {
		in, out := &in.PlaceholdersToOverride, &out.PlaceholdersToOverride
		*out = make([]Placeholder, len(*in))
		copy(*out, *in)
	}
	in.FromResource.DeepCopyInto(&out.FromResource)
	in.ToRepo.DeepCopyInto(&out.ToRepo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalResourceSpec.
func (in *LocalResourceSpec) DeepCopy() *LocalResourceSpec {
	if in == nil {
		return nil
	}
	out := new(LocalResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalResourceStatus) DeepCopyInto(out *LocalResourceStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.TemplatingErrors != nil {
		in, out := &in.TemplatingErrors, &out.TemplatingErrors
		*out = make([]commonv1alpha1.TemplatingError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalResourceStatus.
func (in *LocalResourceStatus) DeepCopy() *LocalResourceStatus {
	if in == nil {
		return nil
	}
	out := new(LocalResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Placeholder) DeepCopyInto(out *Placeholder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Placeholder.
func (in *Placeholder) DeepCopy() *Placeholder {
	if in == nil {
		return nil
	}
	out := new(Placeholder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}
