//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplatingError) DeepCopyInto(out *TemplatingError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplatingError.
func (in *TemplatingError) DeepCopy() *TemplatingError {
	if in == nil {
		return nil
	}
	out := new(TemplatingError)
	in.DeepCopyInto(out)
	return out
}
